name: Documentation

on:
  push:
    branches: [main]
    paths:
      - ".github/workflows/docs.yml"
      - "conda_exec/**"
      - "docs/**"
      - "pyproject.toml"
  pull_request:
    paths:
      - "docs/**"
      - "conda_exec/**"
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  docs:
    name: Build documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
        with:
          persist-credentials: false
      - uses: prefix-dev/setup-pixi@ba3bb36eb2066252b2363392b7739741bb777659 # v0.8.1
        with:
          environments: docs
      - run: pixi run -e docs sphinx-build -b dirhtml docs docs/_build/dirhtml
      - uses: actions/upload-pages-artifact@56afc609e74202658d3ffba0e8f6dda462b719fa # v3
        with:
          path: docs/_build/dirhtml

  pages:
    name: Deploy to GitHub Pages
    needs: docs
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    permissions:
      pages: write # deploy to GitHub Pages
      id-token: write # verify the deployment originates from this workflow
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@d6db90164ac5ed86f2b6aed7e0febac5b3c0c03e # v4
